# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
- package-ecosystem: docker
  directory: /
  schedule:
    interval: daily
    timezone: America/Halifax
  allow:
    - dependency-name: "*"
  ignore:
    # Stops Dependabot from flattening full tags into major-only updates
    - dependency-name: "*"
      versions: ["3", "4", "5", "6", "7"]
- package-ecosystem: maven
  directory: /
  schedule:
    interval: daily
    timezone: America/Halifax
  groups:
    spring-boot:
      patterns:
        - "*spring-boot*"
        - "*spring-cloud*"
- package-ecosystem: maven
  directory: /gatling
  schedule:
    interval: daily
    timezone: America/Halifax
  groups:
    gatling:
      patterns:
        - "*gatling*"
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
    timezone: America/Halifax
- package-ecosystem: docker
  target-branch: v1.3
  directory: /
  schedule:
    interval: daily
    timezone: America/Halifax
- package-ecosystem: maven
  target-branch: v1.3
  directory: /
  schedule:
    interval: daily
    timezone: America/Halifax
- package-ecosystem: github-actions
  target-branch: v1.3
  directory: /
  schedule:
    interval: daily
    timezone: America/Halifax
  ignore:
    # Block any tag updates where the version part is major only
    - dependency-name: "*"
      versions: ["3-amazoncorretto*"] # maven
