package jasper.repository;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.annotation.Profile;
import org.springframework.stereotype.Repository;

@Repository
@Profile("sqlite")
public class BackfillRepositoryImplSqlite implements BackfillRepository {
	private static final Logger logger = LoggerFactory.getLogger(BackfillRepositoryImplSqlite.class);

	@Override
	public int backfillMetadata(String origin, int batchSize) {
		logger.warn("{} Bulk backfill disabled for SQLite, metadata will be regenerated by background backfill", origin);
		return 0;
	}
}
