package jasper.repository;

import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import jasper.DisabledOnSqlite;
import jasper.IntegrationTest;
import jasper.repository.spec.SortSpec.TagValueSort;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.junit.jupiter.EnabledIf;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.stream.Collectors;

import static org.assertj.core.api.Assertions.assertThat;

@IntegrationTest
public class IndexRepositoryIT {

	@Autowired
	IndexRepository indexRepository;

	@Autowired
	JdbcTemplate jdbc;

	@PersistenceContext
	EntityManager em;

	@Test
	void testBuildAndDropTags() {
		indexRepository.dropTags();
		indexRepository.buildTags();
		indexRepository.dropTags();
	}

	@Test
	void testBuildAndDropSources() {
		indexRepository.dropSources();
		indexRepository.buildSources();
		indexRepository.dropSources();
	}

	@Test
	void testBuildAndDropPublished() {
		indexRepository.dropPublished();
		indexRepository.buildPublished();
		indexRepository.dropPublished();
	}

	@Test
	void testBuildAndDropModified() {
		indexRepository.dropModified();
		indexRepository.buildModified();
		indexRepository.dropModified();
	}

	@Test
	void testUpdateHotTags() {
		indexRepository.updateHotTags(List.of("plugin/progress:num", "tags->plugin/duration:dur", "plugin/title", "invalid'tag"));
		indexRepository.updateHotTags(List.of());
	}

	List<String> hotTagIndexes() {
		return jdbc.queryForList("SELECT indexname FROM pg_indexes WHERE tablename = 'ref' AND indexname LIKE 'ref\\_hot\\_%' ORDER BY indexname", String.class);
	}

	@Test
	void testBuildAndDropIgnored() {
		indexRepository.dropIgnored();
		indexRepository.buildIgnored();
		indexRepository.dropIgnored();
	}

	@Test
	void testBuildAndDropCascade() {
		indexRepository.dropCascade();
		indexRepository.buildCascade();
		indexRepository.dropCascade();
	}

	@Test
	void testBuildAndDropRegen() {
		indexRepository.dropRegen();
		indexRepository.buildRegen();
		indexRepository.dropRegen();
	}

	@Test
	void testBuildTwice() {
		indexRepository.buildModified();
		indexRepository.buildModified();
		indexRepository.buildIgnored();
		indexRepository.buildIgnored();
		indexRepository.buildCascade();
		indexRepository.buildCascade();
		indexRepository.buildRegen();
		indexRepository.buildRegen();
	}

	String explainPostgres(String sql) {
		em.createNativeQuery("SET LOCAL enable_seqscan = off").executeUpdate();
		return ((List<?>) em.createNativeQuery("EXPLAIN " + sql).getResultList()).stream()
			.map(Object::toString)
			.collect(Collectors.joining("\n"));
	}

	// SQL generated by Hibernate for RefRepository.clearIgnored, getRefCascade and getRefBackfill

	@Test
	@DisabledOnSqlite
	@Transactional
	void testIgnoredIndexUsedPostgres() {
		indexRepository.buildIgnored();
		assertThat(explainPostgres("""
			update ref r1_0 set metadata=jsonb_set(r1_0.metadata, '{ignored}', 'false'::jsonb, true)
			where r1_0.origin='@test' and r1_0.modified<=now() and ( r1_0.metadata )->>( 'ignored' )='true'"""))
			.contains("ref_ignored_index");
	}

	@Test
	@DisabledOnSqlite
	void testBuildAndDropHotTags() {
		var progress = IndexRepositoryImplPostgres.hotTagIndexName(TagValueSort.parse("plugin/progress:num"));
		var duration = IndexRepositoryImplPostgres.hotTagIndexName(TagValueSort.parse("plugin/duration:dur"));
		var progressText = IndexRepositoryImplPostgres.hotTagIndexName(TagValueSort.parse("plugin/progress"));
		assertThat(progress).startsWith("ref_hot_plugin_progress_value_num_");
		assertThat(progressText).isNotEqualTo(progress);
		assertThat(IndexRepositoryImplPostgres.hotTagIndexName(TagValueSort.parse("a".repeat(200) + ":dur")).length()).isLessThanOrEqualTo(63);

		indexRepository.updateHotTags(List.of("plugin/progress:num", "tags->plugin/duration:dur", "invalid'tag"));
		assertThat(hotTagIndexes()).containsExactlyInAnyOrder(progress, duration);

		indexRepository.updateHotTags(List.of("plugin/progress:num", "plugin/progress"));
		assertThat(hotTagIndexes()).containsExactlyInAnyOrder(progress, progressText);

		indexRepository.updateHotTags(List.of());
		assertThat(hotTagIndexes()).isEmpty();
	}

	@Test
	@DisabledOnSqlite
	@Transactional
	void testCascadeIndexUsedPostgres() {
		indexRepository.buildCascade();
		assertThat(explainPostgres("""
			select r1_0.url from ref r1_0
			where ( r1_0.metadata )->>( 'cascade' )='true' and ( '@test'='' or r1_0.origin='@test' or r1_0.origin like ('@test'||'.%') escape '' )
			order by r1_0.modified desc fetch first 1 rows only"""))
			.contains("ref_cascade_index");
	}

	@Test
	@DisabledOnSqlite
	@Transactional
	void testRegenIndexUsedPostgres() {
		indexRepository.buildRegen();
		assertThat(explainPostgres("""
			select r1_0.url from ref r1_0
			where ( r1_0.metadata is null or ( r1_0.metadata )->>( 'modified' ) is null or ( r1_0.metadata )->>( 'regen' )='true' )
				and ( '@test'='' or r1_0.origin='@test' or r1_0.origin like ('@test'||'.%') escape '' )
			order by r1_0.modified desc fetch first 1 rows only"""))
			.contains("ref_regen_index");
	}

	String explainSqlite(String sql) {
		return ((List<?>) em.createNativeQuery("EXPLAIN QUERY PLAN " + sql).getResultList()).stream()
			.map(row -> row instanceof Object[] cols ? cols[cols.length - 1].toString() : row.toString())
			.collect(Collectors.joining("\n"));
	}

	static String field(String metadata, String key) {
		var path = "'$.\"' || REPLACE('" + key + "', '\"', '\"\"') || '\"'";
		return "( CASE WHEN json_type(" + metadata + ", " + path + ") IN ('true', 'false') THEN json_type(" + metadata + ", " + path + ") ELSE CAST(json_extract(" + metadata + ", " + path + ") AS TEXT) END )";
	}

	@Test
	@EnabledIf(expression = "#{environment.acceptsProfiles(T(org.springframework.core.env.Profiles).of('sqlite'))}", loadContext = true)
	@Transactional
	void testIgnoredIndexUsedSqlite() {
		indexRepository.buildIgnored();
		assertThat(explainSqlite("""
			update ref set metadata=json_set(metadata, '$.' || REPLACE(REPLACE('{ignored}', '{', ''), '}', ''), CASE WHEN 1 IS NOT NULL THEN json('false') ELSE json('false') END)
			where origin='@test' and modified<='2020-01-01T00:00:00Z' and %s='true'""".formatted(field("metadata", "ignored"))))
			.contains("ref_ignored_index");
	}

	@Test
	@EnabledIf(expression = "#{environment.acceptsProfiles(T(org.springframework.core.env.Profiles).of('sqlite'))}", loadContext = true)
	@Transactional
	void testCascadeIndexUsedSqlite() {
		indexRepository.buildCascade();
		assertThat(explainSqlite("""
			select r1_0.url from ref r1_0
			where %s='true' and ( '@test'='' or r1_0.origin='@test' or r1_0.origin like ('@test'||'.%%') )
			order by r1_0.modified desc limit 1""".formatted(field("r1_0.metadata", "cascade"))))
			.contains("ref_cascade_index");
	}

	@Test
	@EnabledIf(expression = "#{environment.acceptsProfiles(T(org.springframework.core.env.Profiles).of('sqlite'))}", loadContext = true)
	@Transactional
	void testRegenIndexUsedSqlite() {
		indexRepository.buildRegen();
		assertThat(explainSqlite("""
			select r1_0.url from ref r1_0
			where ( r1_0.metadata is null or %s is null or %s='true' )
				and ( '@test'='' or r1_0.origin='@test' or r1_0.origin like ('@test'||'.%%') )
			order by r1_0.modified desc limit 1""".formatted(field("r1_0.metadata", "modified"), field("r1_0.metadata", "regen"))))
			.contains("ref_regen_index");
	}
}
