services:
  web:
    environment:
      SPRING_PROFILES_ACTIVE: prod,jwt,storage,file-cache,scripts,proxy,sqlite
      SPRING_DATASOURCE_URL: jdbc:sqlite:file:jasper-test?mode=memory&cache=shared
      SPRING_DATASOURCE_USERNAME: ''
      SPRING_DATASOURCE_PASSWORD: ''
    depends_on:
      db:
        condition: service_started
        required: false
  repl-web:
    environment:
      SPRING_PROFILES_ACTIVE: prod,sqlite
      SPRING_DATASOURCE_URL: jdbc:sqlite:file:jasper-test?mode=memory&cache=shared
      SPRING_DATASOURCE_USERNAME: ''
      SPRING_DATASOURCE_PASSWORD: ''
    depends_on:
      repl-db:
        condition: service_started
        required: false
  tunnel-web:
    environment:
      SPRING_PROFILES_ACTIVE: prod,storage,sqlite
      SPRING_DATASOURCE_URL: jdbc:sqlite:file:jasper-test?mode=memory&cache=shared
      SPRING_DATASOURCE_USERNAME: ''
      SPRING_DATASOURCE_PASSWORD: ''
    depends_on:
      tunnel-db:
        condition: service_started
        required: false
  db:
    profiles:
      - never
  repl-db:
    profiles:
      - never
  tunnel-db:
    profiles:
      - never
